### PR TITLE
one route added

### PR DESCRIPTION
**Pull request by HarvinderSinghDiwan**
Chal be loude, pull krle

### CODE REVIEW

**Review by vvicky30 — CHANGES_REQUESTED** [review]
Bhosdike route ka naam change kr

**Comment by HarvinderSinghDiwan** [comment]
Thike benchod

**Comment by HarvinderSinghDiwan** [comment]
Lekin kya naam rkhu wo to bta

**Comment by vvicky30** [comment]
MuhammedGuddu rkh

**Comment by HarvinderSinghDiwan** [comment]
gand mra ballifarziwara rkhunga

**Comment by vvicky30** [comment]
krle yrr

**Review by vvicky30 — APPROVED** [review]
krhi liya na apne mn ki bhosdike.

**Review by vvicky30 — APPROVED** [review]
approved

**Pull request merged**
